project:
  type: book
  output-dir: docs
  
lang: pt-BR

book:
  title: "Modelagem de Distribuição de Espécies no R"
  reader-mode: true
  
  page-footer:
    left: |
      Modelagem de Distribuição de Espécies no R foi escrito por Maurício H. Vancine.
    right: |
      Este livro foi feito com [Quarto](https://quarto.org){target="_blank"}.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://mauriciovancine.github.io/book-sdm-r
  repo-url: https://github.com/mauriciovancine/book-sdm-r
  chapters:
    - index.qmd
    - intro.qmd
  
    - part: theory.qmd
      chapters:
        - cap01.qmd
    
    - part: data.qmd
      chapters:
       - cap02.qmd
       - cap03.qmd
    
    - part: model.qmd
      chapters:
        - cap04.qmd
        - cap05.qmd
        - cap06.qmd
        - cap07.qmd

    - part: evaluation.qmd
      chapters:
       - cap08.qmd
       - cap09.qmd
       - cap10.qmd
       
    - part: prediction.qmd
      chapters:
       - cap11.qmd
       - cap12.qmd
       - cap13.qmd
       - cap14.qmd
    
    - part: application.qmd
      chapters:
       - cap15.qmd
       - cap16.qmd
       - cap17.qmd
       - cap18.qmd
       - cap19.qmd
       - cap20.qmd
       - cap21.qmd
       - cap22.qmd
       - cap23.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - book-sdm-r.scss
    code-link: true
    
    author-meta: "Maurício H. Vancine"
    callout-appearance: simple

execute: 
  warning: false 
  message: false

editor: source

