# Algoritmos

## Algoritmos para estimar o nicho das espécies

Os métodos correlativos de modelagem de nicho ecológico podem ser classificados em três grandes grupos: presença/ausência, somente de presença e presença/background (veja Franklin 2009, Peterson et al. 2011). A classe de modelos de presença/ausência contrapõem variáveis ambientais para mostrar as condições adequadas para ocorrência da espécie levando em consideração também as localidades onde ela não ocorre. Essa classe de modelos pode ser interessante para predizer o nicho realizado da espécie uma vez que os pontos de ausências verdadeiros podem inferir indiretamente a influência negativa das interações bióticas (dimensão bionômica) sobre o nicho da espécie (Jimenéz-Valverde et al. 2008). Estes tipos de modelos incluem modelos lineares generalizados (GLM), a análise discriminante (Lachenbruch 1975), a regressão logística (Hosmer & Lemeshow 1989), os modelos aditivos generalizados (GAM; Hastie & Tibshirani 1990), dentre outros. Os modelos de presença e ausência tendem a estimar um nicho próximo ao nicho realizado, por inferirem a influência bionômica nos dados de ausência (Figura XX).

Nos modelos de presença/background são comparadas as condições ambientais dos dados de presença com as condições disponíveis na área de estudo (background) para determinar o nicho das espécies. Isso é feito usando alguns pontos aleatórios a partir do background como forma de avaliar os modelos baseando-se nas omissões (predição de ausência em um local onde a espécie é presente) e comissões (predição de ocorrência dentro da área de ocorrência conhecida) (Peterson et al. 2011). Nesse sentido, os resultados desse tipo de modelos são predições intermediárias entre o nicho realizado e o nicho potencial (Jimenéz-Valverde et al. 2008) (Figura XXXX). Os algoritmos mais conhecidos que usam essa metodologia são: algorítmo genético (Genetic Algorithm for Rule-set Production - GARP) (Stockwell & Peters 1996), o de Máxima Entropia (MaxEnt) (Phillips et al. 2006) e o suporte de vetores (Support Vector Machine - SVM) (Tax & Duin 2004).

Por fim, os métodos somente de presença sobrepõem os pontos de presença das espécies com as variáveis ambientais para obter a gama de condições requeridas. Os algoritmos de Distância de Mahalanobis (Farber & Kadmon 2003), de envelope multidimensional (MDE) utilizado pelo BIOCLIM (Nix 1986), Domain (Carpenter et al. 1993) e o ENFA (Environmental Niche Factor Analysis) (Hirzel et al. 2002) são exemplos da utilização dos métodos somente de presença.

O Bioclim é um dos primeiros algoritmos usados para modelar a distribuição de espécies. Ele é baseado em “envelopes” bioclimáticos (Busby 1986, Busby 1991). Esse algoritmo estabelece um “envelope” retilíneo que delimita as condições ambientais adequadas à sobrevivência da espécie. Os limites que definem o envelope são obtidos pela amplitude de cada variável ambiental relacionada aos pontos de ocorrência da espécie. Se uma espécie, por exemplo, ocorre em locais com regime de temperatura média entre 20 ºC e 22 ºC e com precipitação de 2000 mm a 2800 mm, então o algoritmo seleciona todas as regiões geográficas que apresentam valores dentro desses intervalos das variáveis (esse é o envelope retilíneo). Somando-se todas as regiões geográficas que possuem variáveis dentro dos limites estabelecidos pelo envelope encontra-se a distribuição potencial da espécie. De outra forma, os limites do envelope podem ser definidos estatisticamente a partir dos intervalos de confiança (95%, por exemplo) (Lima-Ribeiro & Diniz-Filho 2013). Esse tipo de modelo tente a extrapolar o nicho realizado da espécie e modela um nicho ‘similar’ ao nicho potencial (Jiménez-Valverde et al. 2008) (Figura XXX).

Diferentemente do Bioclim, os métodos de distância ambiental (distância Euclidiana e distância de Gower) e os modelos baseados em análises multivariadas (distância de Mahalanobis e ENFA) assumem a existência de um ótimo ecológico para a sobrevivência da espécie, centroide das condições ambientais (Carpenter et al. 1993). Após a delimitação dos centroides são estabelecidos envelopes circulares ou elipsoidais ao seu redor. As distâncias Euclidianas e de Gower calculam a distância, no espaço ambiental, entre o centroide e cada um dos pontos de ocorrência conhecidos. Por definição, a adequabilidade do habitat e a distância são inversamente proporcionais, ou seja, quanto menor a distância entre o centroide e o ponto, maior a sua adequabilidade. A distância de Mahalanobis e o ENFA calculam o centroide e a distância do centroide aos pontos baseados em um espaço ambiental multivariado representado pelos valores dos vetores das médias entre as variáveis e a covariância entre elas (Faber & Kadmon 2003).

Falar sobre os modelos de presença/background

## Consenso entre os algoritmos (*ensembles*) 



## Softwares e pacotes para construção dos ENMs

Recentemente, uma ferramenta inovadora surgiu para auxiliar na preparação dos dados de entrados dos ENMs, além de outras funcionalidades. Brown (2014) disponibilizou um pacote de ferramentas para o software ArcGIS®, que permite, segundo o site que hospeda o pacote de ferramentas: “SDMtoolbox é uma caixa de ferramentas ArcGIS baseada em Python para estudos espaciais de ecologia, evolução e genética. SDMtoolbox consiste em uma série de scripts em Python (71 e crescendo), projetado para automatizar complexas análises no ArcMap® (ESRI). Um grande conjunto de ferramentas foi criado para complementar os modelos de distribuição de espécies MaxEnt (SDMs) ou para melhorar o desempenho preditivo dos modelos MaxEnt (...). O SDMtoolbox não se limita a análises de modelos MaxEnt e muitas ferramentas também estão disponíveis para uso em outros dados (ou seja, redes de haplótipos) ou os resultados de outros métodos SDM (tradução livre)”.

Além da disponibilidade dos dados de entrada (ocorrências e variáveis ambientais) e ferramentas para suas edições, que são primordiais para a construção de modelos de nicho, softwares que constroem os modelos também se tornaram acessíveis aos usuários, como entidades com interface simplificadas e acesso gratuito, que seguiram a revolução “Código Aberto” ou do inglês Open Source. Diversas iniciativas podem ser citadas, tanto no âmbito internacional, como o projeto DIVA-GIS (), o projeto GARP () e MaxEnt (), como o projeto brasileiro do openModeller (), desenvolvido pelo CRIA (), que foi o primeiro programa a integrar todos os algoritmos de modelos de nicho em uma plataforma única. Além dessas interfaces, diversos pacotes têm sido desenvolvidos e implementados no software R (R Core Team 2017), que possui ampla divulgação e conhecimento entre os ecólogos. Esses pacotes funcionam através de comandos digitados pelo usuário. Atualmente três pacotes têm sido utilizados para a construção dos modelos: “biomod2” (), “dismo” () e mais recentemente “sdm” (), que ainda está em fase de finalização.

## Descrição do processo de construção dos ENMs


## Dificuldades, desafios e perspectivas do uso de ENMs

Assim com toda ferramenta que cresce rapidamente, a modelagem de nicho ecológico também possui seu lado “obscuro”, se assim pode-se dizer. Com a facilidade na obtenção de dados, muitos pesquisadores e estudantes tem utilizado essa ferramenta de forma desenfreada e sem o conhecimento adequado. Isso lançou na literatura diversos artigos com predições erradas e distorcidas, como pode se notar em alguns trabalhos lançados na literatura recente. Isso pode ser considerado um problema grave na biologia da conservação, por exemplo. Predições erradas podem levar a tomadas de decisões erradas e que envolvem grandes quantias de dinheiro gastos às avessas, sem eficiência. Dessa forma, pode-se dizer que se forem inseridos dados ruins, com variáveis inadequadas e sem conhecimento prévio dos algoritmos, os modelos gerados serão piores ainda. Assim, deixamos aqui a mensagem que modelar é uma arte e assim como outras áreas da ecologia necessita de desenho experimental prévio e muita reflexão para a escolha do “melhor modelo”. Não será o primeiro e nem o último o “melhor”. Construir modelos de nicho ecológico não é apenas colocar variáveis e apertar botões ou rodar “scripts”. Modelar não é uma caixa preta. Para se modelar é necessário respeitar passos e premissas. Maiores informações sobre técnicas, conceitos e premissas necessárias para gerar modelos de nicho podem ser obtidas em Jiménez-Valverde et al. (2008), Elith & Leathwich (2009) e nos livros de Franklin (2009) e Peterson et al. (2011). 

A maioria dos trabalhos que utilizaram modelos de nicho ecológico baseou-se apenas em variáveis climáticas. Isso não é errado. Como discutido por Grinell (1917), o clima é um fator que delimita a distribuição das espécies. Isso é indiscutível e serviu como base na discussão da viabilidade do uso de modelos de nicho (Peterson & Soberón (). Soberón & Nakamura (2009) – Diagrama BAM). Contudo, no atual cenário do Antropoceno em que vivemos, a modificação da paisagem se tornou outro fator limitante na distribuição de espécies e o uso de variáveis de paisagem em ENMs está sendo totalmente negligenciado. Acreditamos que isso acontece pelo fato de existirem poucos especialistas em Ecologia de paisagem no Brasil e, principalmente, não existirem métricas de paisagem que possam ser usadas na construção dos modelos. A utilização de métricas de paisagem vai além da utilização de características simplistas como tamanho do remanescente florestal. O ideal, nesse caso, é utilizar métricas de paisagem que sejam capazes de demonstrar o efeito da paisagem na dispersão e na persistência local das espécies tais como, medidas de heterogeneidade ambiental, conectividade dos fragmentos e principalmente características referentes às matrizes. Esses dados ainda não estão amplamente disponibilizados para o Brasil e por isso não estão sendo utilizados nos modelos de nicho. Contudo, a reflexão sobre como obter essas métricas e principalmente de como inserir essas métricas nos modelos de nicho é certamente uma necessidade urgente para aumentar a realidade dos modelos gerados. 

Um desafio nesse contexto é o armazenamento dos dados para gerar os modelos, assim como as saídas dos modelos. Há a necessidade de grande espaço de armazenamento, no caso Terabytes de informações das camadas grade (raster). Dessa forma, faz-se necessário o uso de servidores para armazenar tais dados. Além disso, por mais que nossos computadores tenham aumentado à capacidade de processamento, a computação na nuvem tem se mostrado uma poderosa ferramenta para realizar esse tipo de análise. Apesar disso, há ainda pouco ou quase nenhum incentivo ou conhecimento para realizar esse tipo de procedimento. Aliado ao desconhecimento, temos a baixa capacidade de transferência de dados, tanto para subir (upload) como baixar essas camadas de resultados (download). Apesar isso, exemplos como o Google Earth Engine pode ser uma solução em curto prazo.
