# Ocorrências

## Pontos de ocorrências	

Assim como a ampla disponibilidade de dados oriundos das atividades socioeconômicas, principal fonte de dados das análises da Ciência de Dados, a Ecologia também atingiu uma expressiva quantidade de dados disponíveis acerca da biodiversidade (Hampton et al. 2013). A maior parte desses dados geralmente é de ocorrência (coordenadas geográficas - latitude e longitude) de presença de espécies, oriundos de levantamentos da composição e abundância de comunidades, dados de coleções, museus, herbários, registros fósseis e mais recentemente, dados gerados de ciência cidadã. A ausência de uma espécie é um dado muito raro de se conseguir e em sua maioria irá depender de diversos fatores, como esforço amostral, métodos de coleta e uma série de outros requisitos. Em grande parte, os dados de ocorrência são georreferenciados, ou seja, as respectivas coordenadas geográficas são adquiridas através de aparelhos de Sistema de Posicionamento Global (Global Positioning System - GPS), que são receptores situados na superfície do planeta que captam micro-ondas emitidas por um conjunto de satélites (Bossle 2016).

Diversas bases foram criadas nas últimas duas décadas, mas três merecem maior destaque. Primeiramente, a base mundial do Global Biodiversity information Facility (GBIF), possui mais de 710 milhões de registros georreferenciados de diversas coleções de todo o mundo, com dados da biodiversidade terrestre e aquática. A segunda e a terceira são bases brasileiras: SpeciesLink criado e mantido pelo CRIA, possui mais de 4 milhões de registros georreferenciados, reunindo dados de ocorrência de quase todos os museus e coleções brasileiras; e o Sistema de Informação sobre a Biodiversidade Brasileira (SiBBr), também com mais de 4 milhões de registros georreferenciados, uma iniciativa do Ministério da Ciência, Tecnologia, Inovações e Comunicações (MCTIC), por meio da sua Secretaria de Políticas e Programas de Pesquisa e Desenvolvimento (SEPED), com suporte técnico do Programa das Nações Unidas para o Meio Ambiente (PNUMA) e apoio financeiro do Fundo Global para o Meio Ambiente (GEF), para reunir diversas informações sobre a biodiversidade brasileira. 

No entanto, outras dezenas de bases de dados de ocorrência estão disponíveis para o mundo e para o Brasil. Acreditamos que as principais foram compiladas nessa revisão e estão disponíveis na Tabela S1. Nós classificamos essas bases segundo as características de origem e grupos taxonômicos dos dados. No total foram compilados 56 sites de bases de dados, organizados nos seguintes grupos: Biodiversidade no mundo (06/07), Biodiversidade no Brasil (03), Biodiversidade marinha (04), Botânica (10), Aves (02), Invertebrados (02), Espécies invasoras (03), Dados paleológicos (15) e Ciência cidadã (12). 
Além dos sites das bases, também compilamos 21 pacotes no software R que fazem buscas ou correções das ocorrências das espécies, listados na Tabela S2. Eles foram classificados com base em sua funcionalidade: Download das ocorrências (13), Mapas das ocorrências (02), Correção e limpeza das ocorrências (04) e Geração de ocorrências de espécies virtuais (02), além de um software específico para criar ocorrências de espécies virtuais (“NicheA”, Qiao et al. 2016). 

## Problemas associados aos dados de ocorrência

Apesar da ampla facilidade de acesso aos dados de ocorrências, diversos problemas e erros podem estar associados a esses dados. Embora essa revisão esteja longe de ser algo substancial na discussão acerca desses problemas, abordamos aqui alguns dos principais erros, sob três aspectos: amostragem, taxonomia e resolução temporal e espacial. Para maiores discussões acerca dessas problemáticas, consultar o capítulo 4 de Franklin (2009) e capítulo 5 de Peterson et al. (2011). 

Primeiramente, o viés de amostragem (esforço amostral não padronizado e/ou lacunas de amostragem) é um problema recorrente no mundo todo, mas principalmente nas regiões tropicais, sobretudo no Brasil, devido à alta diversidade e difícil acesso a todas as localidades (Oliveira et al. 2016). Essas inconsistências geram (para algumas espécies e grupos taxonômicos) super-amostragens, i.e., amostragens excessivas – centenas de pontos de ocorrências muito próximos, ou ainda, subamostragens, i.e., amostragens escassas – poucos e esparsos pontos de ocorrências (Syfert et al. 2013, Beck et al. 2014). Esses desbalanços podem gerar modelos de nicho demasiadamente ajustados para os pontos (super-ajuste) ou impossibilitar a criação de modelos robustos (Kramer-Schadt et al. 2013). Para ambos os problemas há diferentes técnicas para tentar contornar os problemas: para a super-amostragem pode-se realizar uma rarefação dos pontos (seleção de parte dos pontos com algum critério) ou a criação de uma camada raster de viés (bias grid, Kramer-Schadt et al. 2013, Fourcade et al. 2014). Contornar a escassez de pontos é mais complicado e requer algumas técnicas específicas de modelagem, como o leave-one-out, que será mais bem abordado adiante (Pearson et al. 2007, van Proosdij et al. 2016).

Além dos vieses de amostragem, erros de identificação da taxonomia das espécies podem ocorrer tanto em coletas de campo, como em coleções, herbários e museus. Esses erros geralmente estão associados às imprecisões taxonômicas de grupos complexos ou mudanças na taxonomia, que muitas vezes não são atualizadas nas coleções. Para minimizar os erros de identificação taxonômica deve-se, na medida do possível, realizar a conferência do material, mas para a taxonomia não atualizada, pode-se fazer uso de uma lista de sinônimos, para garantir que todos os registros foram levantados.

Por fim, a precisão temporal e espacial são cuidados essenciais para garantir a confiabilidade dos dados de ocorrência. A precisão temporal está relacionada ao ano de coleta: dados coletados no início do século passado, por exemplo, podem não representar o nicho atual da espécie por diversas razões, como efeitos antrópicos das mudanças climáticas ou modificações da paisagem (perda de habitat), ou mesmo naturais, como flutuações populacionais ou migrações. Além disso, como as variáveis de clima tendem a serem mais recentes (1950-atual), registros anteriores podem também não representar o nicho da espécie. 

A precisão espacial diz respeito ao nível de detalhamento das coordenadas geográficas informadas. Por exemplo, coordenadas geográficas com dados apenas de graus (e.g. 23º S e 45º W, ou ainda, 23º 22’ S 45º 20’ W), podem ser pouco precisas, dependendo da resolução espacial das variáveis utilizadas (esse fato será abordado novamente). Além disso, deve-se sempre que possível consultar Gazetteer (dicionário geográfico) para verificar as coordenadas informadas para certa coleta, informadas em município ou locais conhecidos. Por fim, atualmente pode-se fazer uso da ferramenta livre Google Earth® para conferir e refinar as coordenadas.
