# Teoria

## Considerações Iniciais

Quando George E. P. Box (1919-2013), químico e estatístico inglês, afirmou que “Essentially, all models are wrong, but some are useful.” [“Essencialmente, todos os modelos estão errados, mas alguns são úteis.” (tradução livre)] (Box & Norman 1987, p. 424), mal sabia ele que sua frase seria recorrentemente utilizada para defender a utilidade dos modelos em diversas áreas de estudo. Essa frase resume bem duas características principais dos modelos: o erro atrelado aos mesmos e sua utilidade. Modelo, ao menos do ponto de vista das Ciências Naturais, i.e., um modelo científico, pode ser compreendido como uma “representação simplificada da realidade, que se adequa à resolução de algum problema” (Box, 1979). Portanto, a não conformidade total com a realidade pode gerar resistência de seu uso por tomadores de decisão ou mesmo pesquisadores da área ambiental. Ao analisarmos o apontamento de Box, notamos a existência da conjunção “mas”, que contrapõe sua utilidade na resolução de problemas no mundo real. Temos certeza de que os modelos não contemplam toda a complexidade da realidade, contudo, sua utilidade vem justamente do fato de ser uma simplificação de um problema complexo. Assim, os modelos podem servir como um início da procura da resposta para um problema real complexo. 

Uma vez construído um modelo, o mesmo pode ser utilizado para entender um padrão ou processo de interesse modelado e para fazer predições ou extrapolações no tempo e no espaço. Isso nos leva a outro ponto necessário a se abordar sobre os modelos: a relação entre complexidade, proximidade da realidade (quantidade de erros - acurácia) e capacidade de predição de novos dados (generalidade; Figura 1). Geralmente, os modelos utilizados para fazer previsão são calibrados ou ajustados com dados de treino e sua qualidade geralmente é avaliada com o sucesso de predição de novos dados de teste, sendo estes sempre independentes dos dados de treino utilizados no ajuste do modelo. Simplificadamente, o balanço entre complexidade, erro e generalidade é quase sempre inverso. Para que um modelo se aproxime da realidade modelada para os dados de treino, maior deve ser sua complexidade e menor será sua quantidade de erros em relação a esses dados, apesar de sua capacidade de prever novos dados (dados de teste) ser quase sempre baixa. A alta complexidade e a dificuldade de construção tornam esses modelos de difícil interpretabilidade e baixa previsibilidade, quase sempre ocorrendo sobreajuste (overfitting) aos dados de treino, sendo esses modelos de pouca utilidade para previsão de novos dados ou extrapolações (Figura 1, Modelo 1). 

Por outro lado, quanto mais simples for um modelo, mais distante o mesmo será da realidade modelada, pois geralmente possuirá grande quantidade de erros, tanto em relação aos dados de treino, quanto na previsão dos dados de teste. Apesar de sua simplicidade e facilidade de construção e entendimento, esses modelos também possuem baixa previsibilidade, dado que são generalistas (underfitting) e não preveem bem novos dados, sendo também de baixa utilidade para responder perguntas de previsão ou extrapolação (Figura 1, Modelo 3). 

O ideal é que se tenha uma parcimônia na construção dos modelos: eles não podem ser tão complexos (muito próximos à realidade), que não tenhamos capacidade de interpretá-los e não sejam capazes de prever novos dados; nem tão simplórios (se distanciem muito da realidade), com muitos erros ao prever novos dados. Dessa forma, um meio termo deve alcançado, para que a acurácia do modelo seja máxima, i.e., o modelo tenha a menor quantidade de erros, tantos ao se ajustar aos dados de treino, quando ao prever novos dados de teste (Figura 1, Modelo 2). 

Apesar da complexidade atrelada aos modelos preditivos, geralmente matemáticos ou estatísticos, outros tipos de modelos estão presentes no nosso dia-a-dia, desde a construção de maquetes (muito utilizadas em projetos de engenharia e arquitetura), até representações de complexas simulações de diversos algoritmos em poderosos computadores (como o aquecimento global, desenvolvidos pelo IPCC). Desde o advento da Estatística com Karl Pearson, até os recentes avanços de Big Data e Machine Learning, o uso de modelos vem crescendo vertiginosamente. Tal crescimento foi tão grande e repentino que surgiu uma nova área da Ciência, chamada “Ciência de Dados”, que integra conhecimento de estatística e complexas análises computacionais. Esse aumento na utilização de modelos vem justamente do estado atual da disponibilidade de grandes volumes de dados e de computadores com alta capacidade de armazenamento e processamento desses dados.

## Modelos de Nicho Ecológico (ENMs)

Essa revolução no uso de modelos, gradualmente mais complexos, atingiu diretamente a Ecologia. Nas últimas décadas, os avanços estatísticos direcionados à resolução de problemas ecológicos sofisticados, têm elevado o nível das análises estatísticas, principalmente no que diz respeito ao uso de abordagens de verossimilhança, seleção de modelos, métodos Bayesianos, de inteligência artificial e análises multivariadas. Apesar desse avanço, foi no campo dos Modelos de Nicho Ecológico (Ecological Niche Modeling - ENMs), também conhecidos como Modelos de Distribuição de Espécies (Species Distributions Modeling - SDMs; embora exista uma diferença entre as duas denominações; ver Soberón & Pearson (2012) e Soberón et al. (2017), para mais detalhes), que os avanços têm ocorrido de forma mais intensa, com grande incremento na literatura ecológica (Lobo et al. 2010, Zimmermann et al. 2010, Vaz et al. 2015).

## Conceito de nicho ecológico

O primeiro trabalho que determinou o conceito teórico de nicho ecológico foi proposto por Joseph Grinnell em 1917. Grinnell (1917) enfatizou que a distribuição geográfica das espécies era regulada por condições ambientais, onde o nicho de uma espécie é determinado pelo conjunto das condições ambientais toleradas pela mesma e que definem sua distribuição geográfica. Após 10 anos, Elton (1927) publicou um ensaio que confrontava o conceito de nicho ecológico proposto por Grinnell (1917). Para Elton (1927), o nicho de uma espécie é caracterizado pelo papel funcional que a mesma desempenha na comunidade e pela sua inter-relação com outras espécies na teia trófica na qual está inserida. Dessa forma, Elton lançou pela primeira vez, uma visão biótica para o nicho, que se realiza em escalas espaciais restritas, enquanto Grinnell (1917) estabeleceu anteriormente uma visão abiótica, relacionada ao controle ambiental sobre a área de distribuição de uma espécie, em escalas espaciais mais amplas.

Em 1957, trinta anos mais tarde, Hutchinson (1957) definiu o conceito de nicho ecológico mais aceito atualmente. Segundo ele, o nicho ecológico é um hipervolume, formado no hiperespaço n-dimensional (Rn), onde cada dimensão (R), entendida aqui como variável, delimita as condições adequadas à sobrevivência de uma espécie. Segundo Hutchinson, os componentes abióticos (ou cenopoéticos) delimitam o nicho fundamental da espécie, determinando sua sobrevivência frente às condições ambientais. O nicho fundamental é restringido pelas interações bióticas (ou componentes bionômicos), delimitando assim o nicho realizado. Dessa forma, a ideia de Hutchinson contempla as ideias de Grinnell (nicho como condições ambientais) e de Elton (nicho como impacto biológico). Contudo, as dinâmicas temporais e espaciais que o nicho de uma espécie está sujeito não foram consideradas por Hutchinson, da mesma forma que a capacidade de dispersão (movimentação) da espécie no tempo e no espaço. Por exemplo, uma espécie pode suportar determinadas condições ambientais, mas não conseguir alcançá-las, devido a uma barreira geográfica ou pela inexistência dessas condições ambientais no período do tempo que a mesma se encontra. 

De uma maneira indireta, Jackson & Overpeck (2000) incorporaram a dinâmica temporal e espacial das condições ambientais nas ideias de Hutchinson e cunharam o conceito de nicho potencial. Segundo esses autores, nem todas as combinações entre as variáveis ambientais estão disponíveis no mundo real, para certo determinado período temporal. A inexistência de tais combinações faz com que surjam nichos vazios, ou espaços não ocupados dentro do nicho fundamental das espécies. Sendo assim, o nicho potencial de Jackson & Overpeck (2000) é a parte do nicho fundamental Hutchinsoniano existente na natureza, em um determinado período. Considerando que houve mudanças nas condições ambientais ao longo do tempo, porções do nicho fundamental das espécies podem se tornar inexistentes em diferentes períodos, ou seja, diferentes nichos potenciais podem existir para uma mesma espécie, dependendo do momento temporal estudado. Com isso, o nicho de uma espécie é considerado estável ao longo do tempo (uma forte premissa que veremos mais adiante), mas as condições ambientais existentes no planeta é que se modificam e delimitam diferentes nichos potenciais. 

Até esse momento, o nicho ecológico de uma espécie, considerado dentro do contexto dos ENMs, pode ser divido em nicho fundamental (cenário cenopoético), nicho potencial (nicho fundamental existente na natureza) e nicho realizado (influência bionômica no nicho potencial). Além disso, ao considerarmos a capacidade de dispersão das espécies, temos de considerar o nicho ocupado, i.e., a parte acessível do nicho realizado para a espécie, considerando as restrições históricas à dispersão (Colwell & Rangel 2009, Soberón & Nakamura 2009). 

## Diagrama BAM

A fim de sintetizar a teoria de nicho vigente (Hutchinson 1957) e ainda adicionar o movimento ao nicho das espécies, Jorge Soberón propôs, em uma série de publicações, que os conceitos teóricos de nicho ecológicos podem ser unificados em um diagrama de Veem, que ficou conhecido como diagrama BAM (Biotic-Abiotic-Movement; Figura 2; Soberón & Peterson 2005, Soberón 2007, Soberón & Nakamura 2009, Soberón & Arroyo-Peña 2017). Nessa representação, o nicho de uma espécie é definido por um conjunto de três círculos, onde a intersecção de todos gera a distribuição de uma espécie: biótico (B), abiótico (A) e movimento (M). O círculo abiótico (cenopoético) delimita o nicho potencial (A’) ou fundamental (A), i.e., as condições ambientais adequadas à existência da espécie. O círculo biótico (B) (bionômico) restringe o espaço do nicho potencial ou fundamental, no qual a espécie é favorecida (e.g. superior na competição ou presença de um facilitador), que delimita o nicho realizado. A intersecção do nicho realizado com a área acessível (M) delimita o nicho ocupado da espécie, ou seja, é a parte do nicho realizado acessível à espécie (Figura 2). 

Apesar dessa construção teórico-prática da visão de nicho ecológico incluir as relações biológicas, Soberón & Nakamura (2009) afirmam que os fatores bionômicos[DS1.1] são difíceis de serem quantificados no espaço ambiental (relação n-dimensional entre as n variáveis ambientais). Somado a isso, Prinzing et al. (2002) alegam que talvez os fatores bionômicos não afetem diretamente o padrão de distribuição das espécies, quando se considera a macroescala. Sendo assim, as interações bionômicas restringem a ocorrência da espécie em um local específico (microescala), mas não restringe a sua amplitude geográfica (macroescala), sendo considerado um “ruído” na distribuição geográfica das espécies, processo denominado “ruído Eltoniano” por Soberón & Nakamura (2009). Além disso, Brewer & Gaston (2003) afirmam ainda que pode haver uma alta correlação geográfica entre as variáveis cenopoéticas e variáveis bionômicas, reforçando o argumento de dificuldade de discernimento entre os efeitos nas escalas consideradas. Apesar desses pontos, trabalhos mais atuais têm demonstrado que talvez a parte bionômica do nicho possa ser tão influente quanto à parte cenopoética (Soberón & Arroyo-Peña 2017) para delimitar a distribuição de uma espécie (Gravel et al. 2016). 

Um último ponto importante a se tratar sobre o nicho ecológico é a dualidade entre o espaço ambiental e espaço geográfico, i.e., existe uma relação direta entre as condições ambientais favoráveis a uma espécie no espaço ambiental e sua distribuição no espaço geográfico (Soberón & Nakamura 2009). Dessa forma, é possível deduzir a distribuição geográfica de uma espécie, levando em consideração apenas as variáveis cenopoéticas, dado que as espécies ocorrem, isto é, mantém populações viáveis (com taxa de crescimento estável ou positiva), em locais onde as condições ambientais são favoráveis à sua sobrevivência, crescimento e reprodução.[DS2.1]

## Modelos de nicho ecológico

Dessa forma, a modelagem de distribuição de espécies é baseada no conceito de nicho ecológico (Lima-Ribeiro & Diniz-Filho 2013). Sendo assim, os modelos estimam o nicho ecológico de uma espécie no espaço ambiental e o projeta no espaço geográfico, a fim de encontrar sua distribuição geográfica (Austin 2002, Soberón 2007, Colwell & Rangel 2009, Soberón & Nakamura 2009, Peterson et al. 2011). Para a construção desses modelos, ao menos do ponto de vista operacional, são necessários dois conjuntos de dados e uma forma de relacioná-los: 1) informação sobre as espécies (tolerância ambiental ou fisiológica obtidos a partir dos pontos de ocorrência), 2) variáveis ambientais (variáveis preditoras medidas no espaço geográfico) e 3) métodos analíticos (funções ou modelos que irão relacionar as informações sobre as espécies aos preditores ambientais no espaço ambiental; Lima-Ribeiro & Diniz-Filho 2013).

O resultado do processo de modelagem de nicho (que será melhor explicitado abaixo) é um mapa de adequabilidade ambiental que mostra locais mais ou menos adequados à sobrevivência ou persistência da espécie modelada, dado seus requerimentos ecológicos (Lima-Ribeiro & Diniz-Filho 2013). Esse mapa é denominado “distribuição geográfica modelada” ou “mapa preditivo” (Elith & Leathwick 2009, Franklin 2009). Apesar dessa relativa simplicidade na construção dos modelos, diferentes resultados podem ser obtidos, dependendo da quantidade e qualidade das informações sobre as espécies, dos tipos de variáveis ambientais disponíveis e utilizadas, assim como dos tipos de métodos analíticos utilizados para estimar o nicho. 
Existem diferentes métodos capazes de estimar o nicho ecológico de uma espécie e assim sua distribuição geográfica. Esses métodos podem ser divididos em dois tipos: modelos mecanísticos e modelos correlativos. Nos modelos mecanísticos, o nicho das espécies é estimado com base na tolerância fisiológica da espécie (Kearney & Porter 2009). Essas tolerâncias são então utilizadas para encontrar áreas geográficas com dados ambientais semelhantes aos medidos em laboratório para a espécie (Kearney & Porter 2009). Apesar de chegar o mais próximo possível do nicho fundamental da espécie, devido a experimentação (Jiménez-Valverde et al. 2008), esses modelos são de uso restrito, sendo assim considerados modelos “espécie-específico” (Lima-Ribeiro & Diniz-Filho 2013). A restrição no uso desses modelos advém do desconhecimento acerca da tolerância fisiológica de muitas espécies atuais (shortfall Hutchinsoniano; Hortal et al. 2015), além de não haver formas de se encontrar tolerâncias fisiológicas para espécies extintas ou fósseis, o que tornam esses modelos pouco aplicáveis (ver discussão em Guisan & Zimmermann 2000).

Os modelos correlativos são mais generalistas e baseiam-se nas informações ambientais atreladas ao conjunto de pontos de ocorrência de uma espécie, para assim estimar seu nicho ecológico e encontrar condições ambientais favoráveis à sua ocorrência no espaço geográfico (Pearce & Ferrier 2000, Guisan et al. 2002, Thuiller 2003, Peterson et al. 2011, Lima-Ribeiro & Diniz-Filho 2013). Dessa forma, os modelos correlativos têm como premissa que a distribuição geográfica das espécies é resultado de seus requisitos ambientais (dimensão abiótica de seu nicho), e indicam regiões geográficas com características ambientais semelhantes àquelas encontradas nos locais onde a espécie foi observada inicialmente (Franklin 2009, Peterson et al. 2011, Lima-Ribeiro & Diniz-Filho 2013). Nesta revisão, apenas os modelos correlativos serão apresentados e discutidos, dado a sua maior usabilidade.

Nos próximos tópicos, as fontes de dados sobre as espécies (ocorrências) e variáveis ambientais serão mais bem descritas, assim como os principais softwares de Sistemas de Informação Geográfica (SIG). Tópicos separados para cada fonte de dados irão tratar dos principais erros e vieses associados tanto a ocorrências, quanto a variáveis ambientais. Além disso, serão também tratados os algoritmos associados aos modelos correlativos e os principais softwares que preparam os dados e realizam a modelagem de nicho. 

Dentre os principais softwares utilizados para o desenvolvimento dos ENMs, destacamos a contribuição do software R (R Core Team 2017). A linguagem e o software R foram desenvolvidos pelos professores Ross Ihaka e Robert Gentleman, ambos do Departamento de Estatística da Universidade de Auckland, em Auckland, Nova Zelândia. O projeto foi iniciado em 1993, com uma versão inicial lançada em 1995 e uma versão beta estável em 2000. Desde então, o software R se tornou uma das ferramentas mais utilizadas para análise de diversos tipos de dados e confecção de gráficos por cientistas de diversas áreas, principalmente na área de Ecologia. Existem diversos pacotes (conjunto de funções) específicos para as mais diversas tarefas, inclusive para a criação de ENMs. 

Dado a ampla divulgação e conhecimento da maior parte dos ecólogos acerca do software R, e devido a sua liberdade e praticidade no manejo de dados espaciais, essa revisão focará em listar e descrever os principais pacotes relacionados tanto à aquisição e tratamentos das ocorrências, assim como as operações de dados espaciais e pacotes relacionados à construção dos ENMs.

## Considerações finais

Em resumo, os dados e ferramentas estão disponíveis, com acesso gratuito a qualquer pesquisador para sua utilização através de ferramentas de ENMs. Obviamente esse fato por si só não incentiva o uso dos ENMs nos projetos de conservação ou impactos da infraestrutura ou mesmo no ensino em universidades com cursos de graduação ou pós-graduação. É necessária divulgação, incentivos e, principalmente, aprimoramento no uso dessas técnicas, para que se possa fazer o seu uso correto. Lembramos que apesar dos modelos conterem falhas e erros, eles podem ser a melhor estratégia para preencher lacunas da biodiversidade, prever possíveis impactos e discutir melhores medidas mitigadoras em um cenário de fragmentação como o encontrado no Brasil. 

Este livro vem a acrescentar um material aos trabalhos já publicados na língua portuguesa sobre esse tema: De Marco Jr. & De Siqueira (2009), Giannini et al. (2012) e Lima-Ribeiro & Diniz-Filho (2013).