# Variáveis

Assim como ampla disponibilidade de dados de ocorrência de espécies, o acesso a dados ambientais geoespacializados também teve um aumento exponencial nas últimas décadas. Esses dados são informações espaciais representadas em mapas no formato raster (grid ou matriz), onde cada célula (pixel) representa uma unidade de informação ambiental. Diversas bases de clima, relevo, tipo de solo, uso e cobertura da terra e oceano têm sido disponibilizados em diversas escalas local, regional, mas principalmente global, apesar dos dados climáticos serem os mais utilizados para a construção dos ENMs (Franklin 2009, citação).

Uma das primeiras bases de dados climáticos disponíveis para o mundo todo foi o WorldClim (Hijmans et al. 2005) e recentemente sua segunda versão (Fick & Hijmans 2017). Esses dados são interpolações de temperatura e precipitação de estações meteorológicas para os anos de 1960-1990 (versão 01) e 1970-2000 (versão 02), disponibilizados nas resoluções espaciais (tamanho da célula ou pixel) aproximadas de 20 km, 10 km, 5 km e 1 km. Esse trabalho de Hijmans et al. (2005) foi fundamental para o desenvolvimento dos ENMs, uma vez que disponibilizaram de maneira acessível ‘variáveis bioclimáticas’, que são 19 combinações temporais de temperatura (BIO01-BIO11) e precipitação (BIO12-BIO19). 

Além disso, Hijmans et al. (2005) fizeram diversas projeções climáticas tomando por base os dados do WorldClim versão 01 e utilizando dados dos projetos PMIP3 (Paleoclimate Modelling Intercomparison Project - https://pmip3.lsce.ipsl.fr) para o passado (Holoceno Médio – 6.000 anos atrás, Último Máximo Glacial – cerca de 22.000 anos atrás, e Último Interglacial – ~120.000-140.000 anos trás). Também fizeram projeções utilizando os dados do CMIP5 (Coupled Model Intercomparison Project - http://cmip-pcmdi.llnl.gov/cmip5/) para o futuro (2050 e 2070), adotando diversos cenários de emissão de CO2 (RCP26, RCP45, RCP60 e RCP85, Representative Concentration Pathways – RCP, Meinshausen et al. 2011) e utilizando diversos GCMs (General Circulation Model – Modelo de Circulação Geral, Phillips 1956).

Além do WorldClim, cujos dados são de estações meteorológicas, existem outras bases climáticas. Uma delas utiliza um GCM para a construção dos dados, como é o caso do CHELSA, que é um conjunto de dados climáticos para todo o globo, para o período de 1979-2013, disponível na resolução aproximada de 1 km (Karger et al. 2016). Outras duas bases de dados climáticos, agora utilizando Sensoriamento Remoto (SR), como os dados disponibilizados por Deblauwe et al. (2016 - https://vdeblauwe.wordpress.com/download/) e mais recentemente o MERRAclim (Vega et al 2017), são mais realistas ao medir através da reflectância, bandas espectrais de satélites como MODIS e CHIRPS, que informam a temperatura, precipitação e disponibilidade de água.

Ainda com relação a dados de SR, diversas bases têm disponibilizado informações além de clima, como o caso do EarthEnv (http://www.earthenv.org), que possui dados de heterogeneidade de habitats (Tuanmu & Jetz 2015), consenso de uso da terra (Tuanmu & Jetz 2014), climatologia de cobertura de nuvens (Wilson & Jetz 2016), modelo digital de elevação (Robinson et al. 2014) e variáveis ambientais de água doce (Domisch et al. 2015), sendo que todas as bases, menos modelo digital de elevação que está com 90 m, estão com resolução aproximada de 1 km. Esses tipos de dados, apesar de só estarem disponíveis para o presente, possuem alta resolução espacial e podem ser utilizados durante ou depois do processo de modelagem de nicho para melhorar os resultados de distribuição das espécies (Sobral-Souza et al. in prep.).

Além das bases internacionais citadas, iniciativas brasileiras também têm disponibilizado diversos dados, como o Instituto de Pesquisas Espaciais (INPE), que criou o AMBDATA (http://www.dpi.inpe.br/Ambdata/), e possui dados de clima atual, relevo e vegetação com resolução aproximada de 1 km. Outra importante base de dados é o ecoClimate que possui dados simulados de clima (precipitação, temperatura média, máxima e mínima), para condições modernas (1950-1999), histórico (1900-1949), pré-industrial (~1760), Médio-Holoceno (6ka), Último Glacial Máximo (21ka), Plioceno (3Ma) e futuro (média de 2080-2100), para quatro cenários (RCP2.6, RCP4.5, RCP6.0 e RCP 8.5) e nove modelos climáticos globais que combinam atmosfera-oceano (AOGCMs, Lima-Ribeiro et al. 2015), com resolução aproximada de 50 km.

As bases de dados ambientais disponíveis também foram compiladas na Tabela S3. No total são 83 sites de bases de dados, organizados nos seguintes grupos: Clima (15), Paleoclimático (01), Uso da Terra (16), Paisagem (07), Agricultura (06), Queimadas (01), Socioeconômico (04), Relevo (05), Solos (01), Geologia (03), Hidrologia (05), Oceano (06), Antártida (01), Amazônia (01), Vetor (03), Diversas Bases (15).

Além dos sites das bases ambientais, também listamos 14 softwares de SIG e 12 principais pacotes no software R que fazer download de variáveis ambientais (08) e realizam operações de SIG (2), como manejo de dadas e estatísticas espaciais (09), listadas na Tabela S4. 

## Problemas associados às variáveis ambientais

Diversos problemas podem estar associados às variáveis ambientais, e da mesma forma que os problemas apontados sobre os pontos de ocorrência, essa revisão está muito aquém de abordar todos essas problemáticas. No entanto, tratamos de alguns dos principais erros, sob três aspectos: limites (extensão), resolução (tamanho do pixel) e seleção das variáveis ambientais. Para maiores discussões consultar o capítulo 5 de Franklin (2009) e capítulo 6 de Peterson et al. (2011).

O primeiro deles é a escolha da extensão que se quer utilizar para realizar a modelagem. Essa escolha pode influenciar drasticamente os resultados, por dois principais motivos: o primeiro, o limite onde se modela (polígono onde as camadas raster são ajustadas) define o espaço de movimentação da espécie modelada, i.e., a parte do movimento do diagrama BAM (item 2.2). Sendo assim, a escolha desse limite deve condizer com as condições de dispersão da espécie e ainda abarcar a história biogeográfica de distribuição da espécie no passado (citação), sendo preferível a escolha de unidades ecológicas mais amplas como biomas ou biorregiões. Além disso, para alguns algoritmos (que serão melhor discutidos a frente), ocorre a amostragem de células que representarão a pseudoausência dos modelos e, portanto, o gradiente de variação ambiental da extensão que se modela. Esta influencia as métricas de avaliação dos modelos (serão melhores explicadas adiante), uma vez que limites muito extensos tendem a causar uma falsa estimativa de altos valores de avaliação, assim como o oposto, onde um limite restrito tende a resultar métricas mais baixas. Encontrar a extensão ideal para realizar a modelagem é um dos principais desafios.

Um segundo problema é a escolha da resolução (tamanho dos pixels) das camadas. Essa propriedade é uma característica relacionada ao tipo de dado que essa camada está atrelada: geralmente dados de clima são disponibilizados com tamanho de pixel maior (~1 km a ~50km) e camadas de uso e cobertura ou paisagem com tamanho de pixel menor (~30m a ~1km). A escolha da resolução das variáveis irá depender do interesse do trabalho, assim como da disponibilidade dos dados. No entanto, é importante salientar que pixels menores (alta resolução) tendem a expressar valores com maior acurácia que pixels maiores (baixa resolução). Isso também influenciará na resolução espacial dos pontos de ocorrência: pontos com baixa resolução (informados com graus e minutos – mencionados no item 3.3) podem não ser um problema para camadas com pixels grandes, uma vez que caíram em um pixel com o mesmo valor. No entanto, se esses pontos são utilizados para camadas com pixels menores, a imprecisão associada aos pontos podem gerar problemas na calibração do modelo. Além disso, é importante levar em consideração o tempo de processamento dos softwares: o tempo será maior, quanto maior for a resolução e maior for a extensão das camadas utilizadas, sendo que o bom senso do pesquisador deve imperar nas escolhas.

Uma vez adequado os limites da extensão que se quer modelar (limites do background) e a resolução do raster, o terceiro desafio é lidar com a correlação das variáveis ambientais. Há diversas formas de se definir quais variáveis serão utilizadas para a construção dos ENMs. A primeira delas é utilizar todas as variáveis (sem seleção) disponíveis, e assumir os possíveis efeitos que possam trazer para os modelos, apesar dessa tomada de decisão não ser recomendada e ter sido bastante criticada recentemente (citação). A segunda opção é fazer uma seleção arbitrária (baseada na disponibilidade/facilidade), o que novamente pode comprometer a qualidade dos modelos (citação). Uma terceira forma é realizar uma seleção biológica. Uma vez que se dispõe de algum conhecimento das espécies às respostas ambientais das variáveis utilizadas, poderia se fazer uso da seleção dessa forma, uma vez que ela é mais adequada, mas pode ser menos operacional, pois para muitas espécies há falta de conhecimento básico.

Ainda, numa quarta forma, é possível realizar uma seleção iterativa, ou seja, constroem-se modelos com todas as combinações possíveis entre todas as variáveis e escolhe-se a combinação das variáveis com melhor desempenho (métricas de avaliação que serão tratadas melhor à frente). Apesar de ser uma forma de garantir que todas as possibilidades entre as variáveis foram utilizadas, isso requer um grande esforço computacional, portanto sendo pouco operacional. Adicionalmente a essa seleção, pode-se fazer uso da técnica de Jackknife, onde vários modelos são gerados, excluindo uma variável a cada rodada. Em cada modelo gerado é calculado o ajuste desse novo modelo. A diminuição ou o aumento do ajuste do novo modelo demonstra a importância da variável para a espécie modelada, e esse critério é utilizado para a seleção.

Por fim, numa quinta forma, pode-se fazer a seleção das variáveis através de análises estatísticas descritivas, sendo essa opção mais operacional, tanto do ponto de vista sistemático e reproduzível, quanto computacional. Quando se faz uma seleção estatística, a mesma pode ser realizada para três conjuntos de dados: apenas para os pontos de ocorrência das espécies (os valores das variáveis são extraídas para cada ponto), para um número de pontos criados aleatoriamente dentro do limite modelado, ou ainda utilizar todos os valores das variáveis. É muito provável, principalmente quando se há pouco poucos pontos de ocorrência, que essas abordagens irão trazer resultados diferentes entre si. Nós aconselhamos que a seleção seja realizada para todo o limite modelado, principalmente quando se deseja modelar diversas espécies. Além disso, a seleção apenas para os pontos de ocorrência pode enviesar as avaliações dos modelos, dado que apenas as variáveis não correlacionadas para os pontos foram utilizadas.

Diversas análises estatísticas podem ser utilizadas nessa forma de seleção, de modo que listamos as três principais, com uma variação da segunda. A primeira delas é realizar uma correlação de Pearson entre todas as variáveis e escolher aquelas com menor correlação. Apesar de sua simplicidade, não existe um método analítico que estabeleça o número de variáveis necessárias para representar toda a variância existente ou um critério que estabeleça um limiar para o valor de “r”, abaixo do qual as variáveis são representativas (i.e. não correlacionadas), geralmente adota-se o valor 0.7 em módulo.

A segunda alternativa é realizar uma Análise de Componentes Principais (PCA), em que é realizada uma ordenação dos valores dos pixels em função das variáveis ambientais. Uma primeira forma de se utilizar essa análise é escolher a variável ambiental que mais contribui para cada novo componente principal criado, através dos valores das cargas (loadings). Adota-se o número máximo de PCs que mais contribuíram para a variação dos dados, geralmente analisando o scree plot dos autovalores.

A segunda forma de se utilizar a PCA é através da criação de novas variáveis ambientais raster de entrada dos modelos, utilizando os escores (scores) de cada PC. Sendo assim, escolhe-se através da análise do scree plot certo número de varáveis pela contribuição e transformam-se esses eixos (autovetores) em novas variáveis raster. Apesar de bastante interessante por abarcar toda a variação ambiental existente no background, essas novas variáveis perdem o significado biológico e tornar-se mais difícil, ou mesmo impossível, a transferência de predições para outras áreas/períodos.

Por fim, a terceira análise estatística que pode ser utilizada é a Análise Fatorial (AF). Essa análise descreve a relação das variáveis ambientais em termos de um número menor de variáveis não observáveis (i.e. fatores ou ainda variáveis latentes). Para a realização dessa análise, requer-se que as variáveis possuam alta correção, uma vez que as mesmas serão agrupadas para descrevem cada fator (eixos ortogonais). A utilização da AF é muito parecida com a PCA, sendo que o objetivo também é selecionar as variáveis pela contribuição de cada variável em cada eixo da fatorial. No entanto, a diferença é que podemos escolher o número de eixos que queremos que as variáveis tenham relação com cada eixo da fatorial, melhorando assim essa relação.

O resultado da análise é uma matriz que relaciona cada variável a cada eixo, sendo que os valores, com esse tipo de variável ambiental, irão variar de -1 a 1. Da mesma forma que na correlação de Pearson, escolhem-se os maiores valores absolutos, um para cada eixo, levando em consideração a biologia da espécie. Essa análise, com esse propósito, foi proposta no trabalho de citação. Dessa forma, essa técnica permite selecionar as variáveis originais independentes entre si, então se preserva seu significado biológico, por consequência, a operacionalização e interpretação nos casos de transferência de predições são diretas.